# Generated by Django 4.1.3 on 2022-12-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projecto', '0002_usuarios_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_estudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
