# Generated by Django 4.1.3 on 2023-01-04 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projecto', '0004_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Projecto.usuarios'),
        ),
    ]
