# Generated by Django 4.1.3 on 2023-01-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projecto', '0005_publicacion_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='name_publi',
            field=models.CharField(default='', max_length=100),
        ),
    ]
