# Generated by Django 4.1.3 on 2023-01-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projecto', '0007_rename_username_publicacion_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(upload_to='static/img_u'),
        ),
    ]
