# Generated by Django 4.1.3 on 2023-01-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projecto', '0009_alter_usuarios_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
    ]
