# Generated by Django 4.1.3 on 2023-01-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projecto', '0010_remove_usuarios_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(upload_to='Projecto/static/img_u'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
